// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApi_Task.Models;

[Index("Dept_id", Name = "IX_Courses_Dept_id")]
public partial class Course
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    public int Degree { get; set; }

    public int MinDegree { get; set; }

    public TimeSpan Hourse { get; set; }

    public int? Dept_id { get; set; }

    [InverseProperty("course")]
    public virtual ICollection<CrsResult> CrsResults { get; set; } = new List<CrsResult>();

    [ForeignKey("Dept_id")]
    [InverseProperty("Courses")]
    public virtual Department Dept { get; set; }

    [InverseProperty("corse")]
    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();
}