// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApi_Task.Models;

[PrimaryKey("traniee_id", "course_id")]
[Table("CrsResult")]
[Index("course_id", Name = "IX_CrsResult_course_id")]
public partial class CrsResult
{
    public int id { get; set; }

    public int degree { get; set; }

    [Key]
    public int course_id { get; set; }

    [Key]
    public int traniee_id { get; set; }

    [ForeignKey("course_id")]
    [InverseProperty("CrsResults")]
    public virtual Course course { get; set; }

    [ForeignKey("traniee_id")]
    [InverseProperty("CrsResults")]
    public virtual Traniee traniee { get; set; }
}