// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApi_Task.Models;

[Index("Dept_id", Name = "IX_Instructors_Dept_id")]
[Index("corse_id", Name = "IX_Instructors_corse_id")]
public partial class Instructor
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [Column(TypeName = "money")]
    public decimal salary { get; set; }

    [StringLength(100)]
    public string Address { get; set; }

    public int? Dept_id { get; set; }

    public int? corse_id { get; set; }

    public string Image { get; set; }

    [ForeignKey("Dept_id")]
    [InverseProperty("Instructors")]
    public virtual Department Dept { get; set; }

    [ForeignKey("corse_id")]
    [InverseProperty("Instructors")]
    public virtual Course corse { get; set; }
}