// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebApi_Task.Models;

public partial class ITI_MVCContext : DbContext
{
    public ITI_MVCContext()
    {
    }

    public ITI_MVCContext(DbContextOptions<ITI_MVCContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<CrsResult> CrsResults { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Instructor> Instructors { get; set; }

    public virtual DbSet<Traniee> Traniees { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) { }
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
   /* => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=ITI_MVC;Integrated Security=True")*/

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CrsResult>(entity =>
        {
            entity.HasOne(d => d.course).WithMany(p => p.CrsResults).OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.traniee).WithMany(p => p.CrsResults).OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Traniee>(entity =>
        {
            entity.HasOne(d => d.Dept).WithMany(p => p.Traniees).OnDelete(DeleteBehavior.ClientSetNull);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}