// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApi_Task.Models;

[Table("Traniee")]
[Index("Dept_id", Name = "IX_Traniee_Dept_id")]
public partial class Traniee
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(100)]
    public string Address { get; set; }

    public string Image { get; set; }

    [StringLength(50)]
    public string Grade { get; set; }

    public int Dept_id { get; set; }

    [InverseProperty("traniee")]
    public virtual ICollection<CrsResult>? CrsResults { get; set; } = new List<CrsResult>();

    [ForeignKey("Dept_id")]
    [InverseProperty("Traniees")]
    public virtual Department? Dept { get; set; }
}